### ISSUE TITLE
How to obtain d4j-info for newer bugs?

### ISSUE THREAD

**Issue by Wooza** [xgdsmileboy/SimFix#11]
Hello,

I would like to run SimFix on bugs that were added with later versions of Defects4J.
When trying to run such a bug, SimFix requires some additional information from the d4j-info directory. Where does this information come from or how can I generate/obtain it?
Thank you for your time.

Best regards
Florian

**Comment by xgdsmileboy** [comment]
Hello,

In the directory of `d4j-info`, there are six sub-folders:
* all_tests: records all test cases for each bug, can be obtained from Defects4J.
* failed_tests_ori: record failed test cases with something like stacktrace printed, can be obtained after run `defects4j test`.
* failed_tests: manually format test cases in `failed_tests_ori`.
* src_path: denotes the paths source code and test cases, need manual efforts.
* location: the sub-folder `ochiai` records the fault localization result of SBFL with ochiai formula.
* project.json: denotes the number of methods that need to repair, manual work.

Hope it will help.
Thanks
