### ISSUE TITLE
A potential bug in NodeUtils.java implementation

### ISSUE THREAD

**Issue by DehengYang** [xgdsmileboy/SimFix#12]
In the method `listNodeMatching()` of `NodeUtils.java`, I find a potential bug (if I do not misunderstand): as is shown in the following code snippet of `listNodeMatching()`, the initial value of `index` is supposed to be `-1` rather than `0`. If it is `0`, the `if(index != -1){` condition will always be true.  I am not sure how much impact this would bring. Therefore, I'd like to present such issue for your check and consideration. Thank you.

```
for(int i = 0; i < otherLen; i++){
				if(record[i] == -1){
					int index = 0;
					for(int j = i + 1; j < otherLen; j ++){
						if (record[j] != -1) {
							index = record[j];
							break;
						}
					}
					if(index != -1){
						Node insert = tarNodeList.get(i);
```

**Comment by xgdsmileboy** [comment]
Thanks @DehengYang . The initial value of `index` should be `-1` but not `0`.

**Comment by DehengYang** [comment]
Thanks for the prompt answer!
