### ISSUE TITLE
Would it be possible/easy to run SimFix on any other bug than a D4J bug?

### ISSUE THREAD

**Issue by jose** [xgdsmileboy/SimFix#17]
Hi,

SimFix's documentation mentions a few times D4J and I'm wondering whether would it be possible to run SimFix on any other bug than D4J's bugs? If yes, it would be great if could help me on that.

Thanks in advance.

--
Best,
Jose

**Comment by xgdsmileboy** [comment]
Currently, SimFix can only run on D4J bugs. The reason is SimFix depends on the commands in D4J to compile and run test cases. If you want to run it beyond D4J, at least the patch validation process should be replaced.

Thanks.
