### ISSUE TITLE
您好，请教一下lang和chart修复失败的问题

### ISSUE THREAD

**Issue by ariescc** [xgdsmileboy/SimFix#3]
您好，我们已经按照您的readme配置好了相关环境，并且将工程导入eclipse中可以运行。我们几个人跑了lang和chart均失败了（Failed to repair），不知道是哪里的问题。向您请教一下。谢谢~

**Comment by xgdsmileboy** [comment]
您可以确认一下在测试正确的补丁时，Repair.java中的validate函数是否正确返回，可能是在验证补丁的时候由于系统环境等因素导致验证失败。

**Comment by ariescc** [comment]
您好，我打断点看validate函数返回的是`return ValidateStatus.TEST_FAILED`

这是系统环境的问题吗？

**Comment by xgdsmileboy** [comment]
环境问题会到这这个错误。
