### ISSUE TITLE
执行jar包时出错

### ISSUE THREAD

**Issue by baoqian426** [xgdsmileboy/SimFix#4]
我在ubuntu虚拟机里执行
java -jar simfix.jar --proj_home=/home/baoqian/buggy --proj_name=chart --bug_id=1

出错
UNKNOWN ASTNode type : catch (NoSuchMethodException e) {
  result=object;
}
请问这是什么原因，java版本是1.7的，百忙之中还望简答一下，感谢！！！

**Comment by xgdsmileboy** [comment]
这不是错，SimFix对 catch语句没有解析，所以输出这个log信息，不影响执行。
