### ISSUE TITLE
修复失败

### ISSUE THREAD

**Issue by ClaudiaAurora** [xgdsmileboy/SimFix#5]
您好，我们按照教程配置过程中也遇到了lang和chart修复失败的问题，我看到您的回答说是环境问题，能不能详细说一下是哪个部分的环境出现问题了呢？

**Comment by xgdsmileboy** [comment]
您可以先调试一下试试，看看为什么没有修复，是因为没有产生正确的修复补丁还是正确的修复补丁没有通过测试？如果是因为正确的补丁没有正确通过测试，您可以调试看一下执行外部命令调用时是否输出正确，验证函数为 [ValidateStatus validate(String logFile, CodeBlock buggyBlock)](https://github.com/xgdsmileboy/SimFix/blob/master/src/cofix/main/Repair.java#L447)。导致失败的原因可能是java的原因，请确认你在执行__外部命令调用__的时候使用的是java-7，
