### ISSUE TITLE
Timeout different for different bugs

### ISSUE THREAD

**Issue by manishmotwani3** [xgdsmileboy/SimFix#9]
Hi!,

I was running SImFix on the newer version of Defects4J and for some reason, it didn't generate any patches for any defects. Quick skim through the logs shows that TIMEOUT value used for different defects is different. For example, for Math 1, TIMEOUT = 1080000 while for Chart 1, TIMEOUT = 18000000, and for Time 26, TIMEOUT = 480000. 
Is it intentional for some reason?

**Comment by xgdsmileboy** [comment]
The time limit for each bug is the same, say as 5 hours. However, as presented in out paper, we perform a test purification process, which may cause multiple failing test cases. In such cases, we divide the time into small slots for ONE failing test case, which can be different depending on the numbers of failing test cases, but the TOTAL time is the same.

**Comment by manishmotwani3** [comment]
Thanks for the prompt response. So the TIMEOUT value printed out on terminal at the beginning of the repair process is NOT the timeout (or TOTAL time) for the repair process, right? 
Can you please point me to the file where we can configure the TOTAL time for the repair process?  

=================================================
Project : chart_1	start : 19/09/02 11:53

TIMEOUT : 18000000
...

**Comment by xgdsmileboy** [comment]
> So the TIMEOUT value printed out on terminal at the beginning of the repair process is NOT the timeout (or TOTAL time) for the repair process, right?

Exactly. This timeout is for the repair under current failing test case.

>Can you please point me to the file where we can configure the TOTAL time for the repair process?

Please see [here](https://github.com/xgdsmileboy/SimFix/blob/master/src/cofix/main/Main.java#L103), the default timeout is 300 minutes (or 5 hours).

Hope it will help!

**Comment by manishmotwani3** [comment]
Thank you!
